### ISSUE TITLE
Crash on render of a banner

### ISSUE THREAD

**Issue by AstrumStriker** [diacritics-owo/ensign#1]
Had a pack that had structures with banners crash when adding this mod. In response, I made a pack with only optimisation mods & ensign which crashed when searching banners in the creative menu.

Time: 2024-09-12 13:40:29
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot assign field "field_3665" because "pillar" is null
	at net.minecraft.class_823.method_3546(class_823.java:583)
	at net.minecraft.class_823.method_3569(class_823.java:28)
	at net.minecraft.class_824.method_23080(class_824.java:98)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.minecraft.class_756.method_3166(class_756.java:131)
	at net.minecraft.class_918.method_23179(class_918.java:127)
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$190(class_757.java)
	at net.minecraft.class_757.wrapOperation$bdc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_823.method_3546(class_823.java:583)
	at net.minecraft.class_823.method_3569(class_823.java:28)
	at net.minecraft.class_824.method_23080(class_824.java:98)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.minecraft.class_756.method_3166(class_756.java:131)
	at net.minecraft.class_918.method_23179(class_918.java:127)
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$190(class_757.java)
	at net.minecraft.class_757.wrapOperation$bdc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Block Entity Details --
Details:
	Name: minecraft:banner // net.minecraft.class_2573
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.minecraft.class_756.method_3166(class_756.java:131)
	at net.minecraft.class_918.method_23179(class_918.java:127)
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$190(class_757.java)
	at net.minecraft.class_757.wrapOperation$bdc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Item being rendered --
Details:
	Item Type: minecraft:white_banner
	Item Components: {minecraft:max_stack_size=>16, minecraft:lore=>class_9290[lines=[], styledLines=[]], minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}, minecraft:repair_cost=>0, minecraft:attribute_modifiers=>class_9285[modifiers=[], showInTooltip=true], minecraft:rarity=>COMMON, minecraft:banner_patterns=>class_9307[layers=[]]}
	Item Foil: false
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$190(class_757.java)
	at net.minecraft.class_757.wrapOperation$bdc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (252, 53). Absolute: (505.000000, 107.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 78.284s
	Wall uptime: 72.671s
	High-res time: 52490.949s
	Client ticks: 1288 ticks / 64.400s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['{MINECRAFT_USERNAME}'/18, l='ClientLevel', x=1111.76, y=71.00, z=-92.96]]
	Chunk stats: 961, 783
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,72,80), Section: (at 0,8,0 in 10,4,5; chunk contains blocks 160,-64,80 to 175,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 661 game time, 661 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 149

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, alternate-current, c2me, chunky, cloth-config, dynamic_fps, enhancedblockentities, ensign, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fastipping, immediatelyfast, lithium, modernfix, noisium, owo, rrls, sodium, sodium-extra, vmp

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 142308840 bytes (135 MiB) / 1242562560 bytes (1185 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600 6-Core Processor              
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 7900 GRE
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 16368.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.11029.1008
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.11029.1008
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 29919.63
	Virtual memory used (MiB): 19599.69
	Swap memory total (MiB): 14336.00
	Swap memory used (MiB): 272.13
	Space in storage for jna.tmpdir (MiB): available: 597624.88, total: 952902.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 597624.88, total: 952902.00
	Space in storage for io.netty.native.workdir (MiB): available: 597624.88, total: 952902.00
	Space in storage for java.io.tmpdir (MiB): available: 597624.88, total: 952902.00
	Space in storage for workdir (MiB): available: 597624.88, total: 952902.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		alternate-current: Alternate Current 1.9.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.109+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.109+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.109+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.109+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.109+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.109+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.109+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.109+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chunky: Chunky 1.4.16
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		ensign: Ensign 1.2.0
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fastipping: Fast IP Ping 1.0.4
		ferritecore: FerriteCore 7.0.0
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.13.0
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.19.1+mc1.21
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		owo: oωo 0.12.11+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		railoptimization: RailOptimization 1.2
		rrls: Remove Reloading Screen 5.0.7+mc1.21-fabric
		sodium: Sodium 0.6.0-beta.1+mc1.21
		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1
			com_lodborg_interval-tree: interval-tree 1.0.0
		vmp: Very Many Players 0.2.0+beta.7.165+1.21
	Launched Version: 1.21
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon RX 7900 GRE GL version 3.2.0 Core Profile Context 24.7.1.240711, ATI Technologies Inc.
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, alternate-current, c2me, chunky, cloth-config, dynamic_fps, enhancedblockentities, ensign, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fastipping, immediatelyfast, lithium, modernfix (incompatible), noisium, owo, rrls, sodium, sodium-extra, vmp
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 7600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/18, l='ServerLevel[New World]', x=1111.76, y=71.00, z=-92.96]]
	Active Data Packs: vanilla, fabric, ensign, fabric-convention-tags-v2
	Available Data Packs: bundle, ensign, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -5962828208133130361

**Comment by diacritics-owo** [comment]
Thanks for reporting this. I'll take a look at it later.

**Comment by diacritics-owo** [comment]
I wasn't able to reproduce the issue, but [1.2.1](https://modrinth.com/mod/ensign/version/1.2.1) hopefully fixes it.
